version: 2
jobs:
  build:
    working_directory: ~/deployment-test-api
    docker:
    - image: monstarlab/maven-awscli:3.6.0-jdk-8
    steps:
    - checkout
    - restore_cache:
        keys:
        - deployment-test-api-dependencies-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: deployment-test-api-dependencies-{{ checksum "pom.xml" }}
    - run:
        name: build
        command: mvn clean package
        
        
  deploy-production:
    working_directory: ~/repo
    environment:
    - AWS_DEFAULT_REGION: us-east-2
    - CODE_DEPLOY_S3_BUCKET_NAME: sample-deployment-test
    - CODE_DEPLOY_APPLICATION_NAME: Deployment_Test_API
    - CODE_DEPLOY_GROUP_NAME: Deployment-test_API_prod
    - APP_DIR: .
    docker:
    - image: innovatorjapan/awscli:latest
    steps:
    - attach_workspace:
        at: .
    - run: sh /bin/aws-s3-deploy
    
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
    - deploy-production:
        requires:
        - build
        filters:
          branches:
            only:
            - master
            
